version: '2'
services:
  default:
    links:
      - ehr-repo:ehr-repo
  ehr-repo:
    image: ${REPOSITORY_URI}:${COMMIT_HASH}
    links:
      - db:db
      - localstack:localstack
    environment:
      - AUTHORIZATION_KEYS=auth-key-1
      - EHR_REPO_SKIP_MIGRATION=false
      - S3_BUCKET_NAME=test-bucket
      - DATABASE_USER=deductions_user
      - DATABASE_PASSWORD=secret
      - DATABASE_NAME=deductions_test
      - DATABASE_HOST=db
      - LOCALSTACK_URL=http://localstack:4572
    ports:
    - 3000:3000
  db:
    image: postgres:12.1
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: deductions_user
      POSTGRES_DB: deductions_test
      LC_ALL: C
  localstack:
    image: localstack/localstack:0.10.9
    environment:
      - SERVICES=s3:4572
      - DEBUG=true
      - PORT_WEB_UI=5555
      - LAMBDA_EXECUTOR=local
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - S3_BUCKET_NAME=test-bucket
      - LOCALSTACK_URL=http://localstack:4572
    volumes:
      - ./scripts/create-bucket.sh:/docker-entrypoint-initaws.d/create-bucket.sh
      - /var/run/docker.sock:/var/run/docker.sock
