format_version: 4
common:
  deploy_job: &deploy_job
    resources:
      - docker
    tasks:
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks create_secrets
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks tf_plan_certs create
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks tf_apply
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks tf_plan create
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks tf_apply
      - exec:
          command: /bin/bash
          arguments:
            - -c
            - ./tasks wait_ecs
pipelines:
  "prm-deductions-ehr-repository.dev":
    group: deductions
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
        blacklist:
          - docs/**/*.*
      app:
        pipeline: prm-deductions-ehr-repository
        stage: test_docker
      base_infra:
        pipeline: prm-deductions-infra
        stage: wait_dns_dev
    environment_variables:
      NHS_ENVIRONMENT: dev
    stages:
      - deploy:
          clean_workspace: true
          jobs:
            deploy: *deploy_job
      - functional:
          clean_workspace: true
          jobs:
            test:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks sanity_check
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks test_functional

  "prm-deductions-ehr-repository.test":
    group: deductions
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
        blacklist:
          - docs/**/*.*
      base_infra:
        pipeline: prm-deductions-infra
        stage: wait_dns_test
      dev_env:
        pipeline: prm-deductions-ehr-repository.dev
        stage: functional
    environment_variables:
      NHS_ENVIRONMENT: test
    stages:
      - deploy:
          clean_workspace: true
          jobs:
            deploy: *deploy_job
      - functional:
          clean_workspace: true
          jobs:
            test:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks sanity_check
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks test_functional
      - performance:
          clean_workspace: true
          jobs:
            test:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks test_performance
